version: 2

sources:
  - name: pc4_devanis
    schema: pc4_devanis
    tables:
      - name: yellowtrip_201901
        identifier: yellowtrip_201901
      - name: yellowtrip_201902
        identifier: yellowtrip_201902
      - name: yellowtrip_201903
        identifier: yellowtrip_201903
      - name: yellowtrip_201904
        identifier: yellowtrip_201904
      - name: yellowtrip_201905
        identifier: yellowtrip_201905
      - name: yellowtrip_201906
        identifier: yellowtrip_201906
      - name: yellowtrip_201907
        identifier: yellowtrip_201907
      - name: yellowtrip_201908
        identifier: yellowtrip_201908
      - name: yellowtrip_201909
        identifier: yellowtrip_201909
      - name: yellowtrip_201910
        identifier: yellowtrip_201910
      - name: yellowtrip_201911
        identifier: yellowtrip_201911
      - name: yellowtrip_201912
        identifier: yellowtrip_201912

models:
  - name: stg__yellowtrip_2019
    description: "Stagging Data Yellow Trip 2019"
    columns:
      - name: pickup_datetime
      - name: dropoff_datetime
      - name: passenger_count
      - name: trip_distance
      - name: pickup_locationid
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: dropoff_locationid
        tests:
          - relationships:
              to: ref('taxi_zone_lookup')
              field: locationid
              severity: warn
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: payment_type
      - name: rate_code
      - name: vendor
      - name: total_amount
      - name: extra_type
      - name: congestion_surcharge
  - name: fact_yellowtrip_2019
    description: "Facts Data Yellow Trip 2019"
    columns:
      - name: pickup_datetime
      - name: dropoff_datetime
      - name: passenger_count
      - name: trip_distance
      - name: pickup_locationid
      - name: dropoff_locationid
      - name: fare_amount
      - name: extra
      - name: mta_tax
      - name: tip_amount
      - name: tolls_amount
      - name: improvement_surcharge
      - name: total_amount
      - name: extra_type
      - name: congestion_surcharge
